version: '3.7'

services:
   akaratefelgueiras:
    image: akaratefelgueiras
    build:
      context: .
    environment:
      - ASPNETCORE_URLS=http://*:5005
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "8081:80"