name: Deploy to GitHub Pages

# Run workflow on every push to main
on:
  push:
    branches: [ main ]

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
    # uses GitHub's checkout action to checkout code from the main branch
    - uses: actions/checkout@v2

    # sets up .NET Core SDK 8.0.100
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.100

    # installs python3
    - name: installs python3
      run: apt-get update && apt-get install -y python3

    # restores blazor wasm workloads
    - name: Restore WASM workloads
      run: dotnet workload install wasm-tools-net8

    # publishes Blazor project to the release-folder
    - name: Publish .NET Core project
      run: dotnet publish -c Release -o release --nologo

    # changes the base-tag in index.html from '/' to 'akaratefelgueiras' to match GitHub Pages repository subdirectory
    #- name: Change base-tage in index.html from / to akaratefelgueiras
    #  run: sed -i 's/<base href="\/" \/>/<base href="\/akaratefelgueiras\/" \/>/g' release/wwwroot/index.html

    # copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # add .nojekyll file to tell GitHub pages not to treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Commit wwwroot to GitHub pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot

    
